[package]
name = "namify"
version = "0.1.2"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
env_logger = "0.11.6"
eyre = "0.6.12"
glob = "0.3.2"
log = "0.4.22"
